kind: Service
apiVersion: v1
metadata:
  name: devswags-loadbalancer
  namespace: web
spec:
  type: LoadBalancer
  selector:
    env: testing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000