apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campushub-frontend
  template:
    metadata:
      labels:
        app: campushub-frontend
    spec:
      containers:
        - name: frontend
          image: '{{ .Values.frontend.image }}:{{ .Values.frontend.version }}'
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: campushub-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
