apiVersion: v1
kind: Secret
metadata:
  name: my-mongodb-atlas-secret
type: Opaque
data:
  BackendPORT: {{ .Files.Get "secrets/BackendPORT" | b64enc | quote }}
  mongodbUser: {{ .Files.Get "secrets/mongodbUser" | b64enc | quote }}
  mongodbPass: {{ .Files.Get "secrets/mongodbPass" | b64enc | quote }}