apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Dev-swag-cluster
  region: us-east-2

nodeGroups:
  - name: ubuntu-ng-large
    instanceType: t2.large
    desiredCapacity: 2
    volumeSize: 100
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
