name: Build and Push Docker Image

on:
  push:
    branches:
      - kubernetes-infra # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 # Checkout the repository code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 # Set up Docker Buildx for multi-platform builds

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Set up kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Build and Push Docker Image
        run: |
          docker buildx build -t <Image-Name>:latest -t <Image-Name>:${{ github.sha }} .
          docker buildx build --push -t <Image-Name>:latest -t <Image-Name>:${{ github.sha }} .

      - name: Update Kubernetes Deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cat $HOME/.kube/config
          aws eks update-kubeconfig --name Dev-swag-cluster --region ${{ secrets.AWS_DEFAULT_REGION }}
          kubectl set image deployment/developerswags-deployment developerswag-container=<Image-Name>:${{ github.sha }} -n web
