---
- hosts: NGLoadBalancer
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name:
          - nginx
    - name: Copy Nginx File to LB
      copy:
        src: /home/ubuntu/devops/Projects/02_useTerraform_nginxLoadBalancer_andSetup_docker_instance/nginx_LB.conf
        dest: /etc/nginx/
    - name: Rename File
      shell: "mv /etc/nginx/nginx_LB.conf /etc/nginx/nginx.conf"
    - name: Restart Nginx
      shell: "systemctl restart nginx"
- hosts: webServer
  become: yes
  vars:
    Repo_Name: MyShoes
    GitHub_Url: https://github.com/aslambaba/
  tasks:
    - name: Install Git and Curl
      apt:
        name:
          - git
          - curl
        state: present
    - name: Download Nodejs File And Nginx
      shell: "curl -sL https://deb.nodesource.com/setup_16.x | sudo bash - && apt -y install nodejs && npm install -g npm@8.19.1 && apt install nginx -y"
    - name: Clone MyShoes into WorkerNodes
      shell: "cd ~/ && rm -rf {{Repo_Name}} && git clone {{GitHub_Url}}{{Repo_Name}}"
    - name: Copy Clone File into Nginx Conf
      copy:
        src: ~/{{Repo_Name}}/
        dest: /var/www/html/
        remote_src: yes
    - name: Install Project Dep
      shell: "cd /var/www/html && sudo npm install"
    - name: Copy NginxConf File
      copy:
        src: /home/ubuntu/devops/Projects/02_useTerraform_nginxLoadBalancer_andSetup_docker_instance/nginx.conf
        dest: /etc/nginx/
    - name: Restart Nginx
      shell: "systemctl restart nginx"
    - name: BUILD APPLICATION
      shell: "cd /var/www/html && sudo npm run build"
- hosts: dockerServer
  become: yes
  gather_facts: true
  vars:
    Repo_Name: Camille-project
    GitHub_Url: https://github.com/aslambaba/
  tasks:
    - name: Install Docker
      shell: "apt install docker.io -y"
    - name: Remove Old Repo
      shell: "cd /home/ubuntu/ && rm -rf {{Repo_Name}}"
    - name: Get running containers details2
      docker_host_info:
        containers: yes
      register: docker_info
    - name: Stop & Remove Old Container
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
    - name: Clone new Image
      shell: git clone {{GitHub_Url}}{{Repo_Name}}
    - name: Buildd DockerImage
      shell: "docker build -t aslambaba/camile /home/ubuntu/{{Repo_Name}}/."
    - name: Run Container
      vars:
        TimeStamp: "{{ansible_date_time.epoch}}"
      shell: "sudo docker run --name aslam_camile_proj_{{TimeStamp}} -idt -p 80:80 aslambaba/camile && sudo docker exec aslam_camile_proj_{{TimeStamp}} /etc/init.d/nginx restart"
